### PR TITLE
Create cronable address watcher script

### PR DESCRIPTION
**Pull request by SeiryuZ**
~~[Work in progress]~~
~~Still missing the request to slack's incoming webhook part~~

### CODE REVIEW

**Comment by texm** [comment]
Why not stream from a horizon server?

**Comment by SeiryuZ** [comment]
Hi @texm,

The reason why I don't use the `stream` option is to make this script take as little resources as possible. Since streaming the response will means that we will have another python interpreter loaded at all times for notification. I want to avoid that, after all this is not critical unlike the inflation payout tools / scripts.

I'd rather have the script executed using `cron` for every 1 minute, or even every 10 minute for simplicity. In addition, we don't have to deal with `upstart` / `systemd` to manage the script's restart if it crashes or etc

The downside of this approach is that the notification is not as realtime as compared to streaming from the horizon, but do you think this approach is a no go ?

**Comment by voidburn** [comment]
Is this valid guys? Do you want me to merge it?

**Comment by SeiryuZ** [comment]
Hi @voidburn, this is still work in progress, can you wait for a bit, I'll finish the last part (ping to slack channel) in 24 hours.

This cron script is written per xlm_in_2018, b1tcc, and my conversation on slack

**Comment by voidburn** [comment]
Sure

**Comment by SeiryuZ** [comment]
This script is now executed every minute on my server. It's low impact enough, that I'm comfortable running it on mine. 

It currently watch this donation address ``GDP3J3NCR4MVB6QBQAYDOMWUYV53CAJ43YQIIFQSCU5ITIGESY2ONAUT`` and notifies the Lumenaut's #donation channel on slack

**Comment by voidburn** [comment]
Good to go?

**Comment by SeiryuZ** [comment]
Yeah, it's live right now. So I think merging this should be OK

**Pull request merged**
